project/categories/routes.py
# Modules from Flask Library
from flask import Flask, render_template, request, flash, Blueprint
from flask import session as login_session
from flask import make_response, redirect, jsonify, url_for
# Access database
from project.models import Category, Product, User
from project.db import session
# Services
from project.services.categories import CategoryService
from project.services.auth import AuthService
from project.services.products import ProductService

import random
import string
import httplib2
import json
import requests


# Create Blueprint 'categories'
categories = Blueprint('categories', __name__)


# Instantiate services
category_service = CategoryService()
product_service = ProductService()
auth_service = AuthService()

DEFAULT_CATEGORY_PRODUCT_NUMBER = 8

@categories.route('/')
@categories.route('/categories/')
def showCategories():
    """App route function for main page to show all categories."""
    return render_template('index.html',
                           categories=category_service.get_all_categories(),
                           isLogin=auth_service.is_user_authorized(),
                           latestProducts=(product_service
                           .get_latest_products(DEFAULT_CATEGORY_PRODUCT_NUMBER)))


@categories.route('/categories/<int:category_id>/')
def showCategoryProducts(category_id):
    """App route function to show Products of the selected Category."""
    isLogin = auth_service.is_user_authorized()
    # Pick category selected by user
    category = category_service.get_category_by_id(category_id)
    # Check if user is Creator of Category
    isCreator = False
    if isLogin:
        isCreator = login_session['email'] == category.user.email
    return render_template('category.html',
                           products=(product_service
                                     .get_products_by_category_id(category_id)),
                           categories=category_service.get_all_categories(),
                           category=category,
                           isLogin=isLogin,
                           countProducts=(product_service
                                          .products_count(category_id)),
                           isCreator=isCreator)


@categories.route('/addcategory/', methods=['GET', 'POST'])
def addCategory():
    """App route function to add new Category to the Category Table."""
    if 'email' not in login_session:
        return redirect('/login')
    if request.method == 'POST':
        if request.form['name'] == '':
            flash("Please, enter Category Name")
            return render_template('addcategory.html',
                                   categories=(category_service
                                               .get_all_categories()),
                                   isLogin=auth_service.is_user_authorized())
        newCategory = Category(name=request.form['name'],
                               user_id=login_session['user_id'])
        session.add(newCategory)
        session.commit()
        flash('New Category {} Successfully Created'.format(newCategory.name))
        return redirect(url_for('categories.showCategories'))
    else:
        return render_template('addcategory.html',
                               categories=(category_service
                                           .get_all_categories()),
                               isLogin=auth_service.is_user_authorized())


@categories.route('/editcategory/<int:category_id>/',
                  methods=['GET', 'POST'])
def editCategory(category_id):
    """App route function to edit existing Category."""
    # If user is not logged in, inform him about it and redirect
    if 'email' not in login_session:
        flash("You need to Log In if you want to edit")
        return redirect('/categories')
    # Get category that is selected to be edited
    categoryToEdit = category_service.get_category_by_id(category_id)
    # Check if user is Creator, if not inform that he cannot
    # do changes
    if not login_session['email'] == categoryToEdit.user.email:
        flash("You need to be Creator of the category to be able to edit")
        return redirect('/categories')
    if request.method == 'POST':
        if request.form['name']:
            categoryToEdit.name = request.form['name']
        else:
            flash('Please, enter category name.')
            return render_template('editcategory.html',
                                   categories=(category_service
                                               .get_all_categories()),
                                   isLogin=auth_service.is_user_authorized(),
                                   categoryToEdit=categoryToEdit)
        session.add(categoryToEdit)
        session.commit()
        flash('You successfully \
              updated category to {}'.format(categoryToEdit.name))
        return redirect(url_for('categories.showCategoryProducts',
                                category_id=category_id))
    else:
        return render_template('editcategory.html',
                               categories=(category_service
                                           .get_all_categories()),
                               isLogin=auth_service.is_user_authorized(),
                               categoryToEdit=categoryToEdit)


@categories.route('/deletecategory/<int:category_id>/', methods=['GET', 'POST'])
def deleteCategory(category_id):
    """App route function to delete existing Category"""
    # If user is not logged in, inform him about it and redirect
    if 'email' not in login_session:
        flash("You need to Log In if you want to delete the category.")
        return redirect('/categories')
    # Get category that is selected to be edited
    categoryToDelete = category_service.get_category_by_id(category_id)
    # Check if user is Creator, if not inform that he cannot
    # do changes
    if not login_session['email'] == categoryToDelete.user.email:
        flash("You need to be a Creator of the category\
               to be able to delete it")
        return redirect('/categories')
    # Check for method and do appropriate. If 'POST' -> delete Category,
    # if 'GET' -> render 'deletecategory.html'
    if request.method == 'POST':
        session.delete(categoryToDelete)
        session.commit()
        flash('You successfully deleted \
              category "{}"'.format(categoryToDelete.name))
        return redirect(url_for('categories.showCategories'))
    else:
        return render_template('deletecategory.html',
                               categories=(category_service
                                           .get_all_categories()),
                               isLogin=auth_service.is_user_authorized(),
                               categoryToDelete=categoryToDelete)

project/products/routes.py
# Modules from Flask Library
from flask import Flask, render_template, request, flash, Blueprint
from flask import session as login_session
from flask import make_response, redirect, jsonify, url_for
# Access database
from project.models import Category, Product, User
from project.db import session

# Services
from project.services.categories import CategoryService
from project.services.auth import AuthService
from project.services.products import ProductService

import random
import string
import httplib2
import json
import requests

products = Blueprint('products', __name__)

# Instantiate services
category_service = CategoryService()
product_service = ProductService()
auth_service = AuthService()


@products.route('/categories/<int:category_id>/<int:product_id>/')
def showProduct(category_id, product_id):
    """App route function to show selected product."""
    # Check if user is logged in and save the result in isLogin
    isLogin = auth_service.is_user_authorized()
    # Get category that is selected to be shown
    category = category_service.get_category_by_id(category_id)
    product = product_service.get_product_by_id(product_id)
    # Check if user is Creator of Category or Product
    isCreator = False
    if isLogin:
        isCreator = (login_session['email'] == category.user.email or
                     login_session['email'] == product.user.email)
    return render_template('product.html',
                           categories=category_service.get_all_categories(),
                           category=category, product=product,
                           isLogin=isLogin, isCreator=isCreator)


@products.route('/addproduct/', methods=['GET', 'POST'])
def addProduct():
    """App route function to add new Product to the Product list."""
    # If user is not logged in, inform him about it and redirect
    if 'email' not in login_session:
        return redirect('/login')
    if request.method == 'POST':
        # Check if all the fields are filled out
        if request.form['name'] == '':
            flash("Please, enter product name. \
                  Make sure you fill out all the fields")
            return render_template('addproduct.html',
                                   categories=(category_service
                                               .get_all_categories()),
                                   isLogin=auth_service.is_user_authorized())
        if request.form['image_url'] == '':
            flash("Please, enter product image(link of the image). \
                   Make sure you fill out all the fields")
            return render_template('addproduct.html',
                                   categories=(category_service
                                               .get_all_categories()),
                                   isLogin=auth_service.is_user_authorized())
        if request.form['product_url'] == '':
            flash("Please, enter product URL. \
                  Make sure you fill out all the fields")
            return render_template('addproduct.html',
                                   categories=(category_service
                                               .get_all_categories()),
                                   isLogin=auth_service.is_user_authorized())
        if request.form['description'] == '':
            flash('Please, enter product description. \
                  Make sure you fill out all the fields')
            return render_template('addproduct.html',
                                   categories=(category_service
                                               .get_all_categories()),
                                   isLogin=auth_service.is_user_authorized())

        category = (session.query(Category)
                    .filter_by(name=request.form['category_name']).one())
        newProduct = Product(name=request.form['name'],
                             description=request.form['description'],
                             image_url=request.form['image_url'],
                             product_url=request.form['product_url'],
                             category_id=category.id,
                             user_id=login_session['user_id'])
        session.add(newProduct)
        session.commit()
        flash('New Product {} Successfully Created'.format(newProduct.name))
        return redirect(url_for('categories.showCategoryProducts',
                                category_id=newProduct.category_id))
    else:
        return render_template('addproduct.html',
                               categories=(category_service
                                           .get_all_categories()),
                               isLogin=auth_service.is_user_authorized())


@products.route('/editproduct/<int:category_id>/<int:product_id>/',
                methods=['GET', 'POST'])
def editProduct(category_id, product_id):
    """App route function to edit existing Product."""
    # If user is not logged in, inform him about it and redirect
    if 'email' not in login_session:
        flash("You need to Log In if you want to edit")
        return redirect('/login')
    # Get Product that user wants to edit
    productToEdit = product_service.get_product_by_id(product_id)
    # Check if user is Creator, if not inform that he cannot
    # do changes
    if not login_session['email'] == productToEdit.user.email:
        flash("You need to be a Creator of the Product to edit it")
        return redirect(url_for('products.showProduct',
                                category_id=category_id, product_id=product_id))
    if request.method == 'POST':
        if request.form['name']:
            productToEdit.name = request.form['name']
        if request.form['image_url']:
            productToEdit.image_url = request.form['image_url']
        if request.form['product_url']:
            productToEdit.product_url = request.form['product_url']
        if request.form['description']:
            productToEdit.description = request.form['description']
        session.add(productToEdit)
        session.commit()
        flash('You successfully edited product')
        return redirect(url_for('products.showProduct',
                                category_id=category_id, product_id=product_id))
    else:
        return render_template('editproduct.html',
                               categories=(category_service
                                           .get_all_categories()),
                               isLogin=auth_service.is_user_authorized(),
                               category=(category_service
                                         .get_category_by_id(category_id)),
                               productToEdit=productToEdit)


@products.route('/deleteproduct/<int:category_id>/<int:product_id>/',
                methods=['GET', 'POST'])
def deleteProduct(category_id, product_id):
    """App route function to delete existing product."""
    # If user is not logged in, inform him about it and redirect
    if 'email' not in login_session:
        flash("You need to Log In if you want to delete product")
        return redirect('/login')
    # Get the Product that User wants to delete
    productToDelete = product_service.get_product_by_id(product_id)
    # Check if user is Creator, if not inform that he cannot
    # do changes
    if not login_session['email'] == productToDelete.user.email:
        flash("You need to be a Creator of the Product to delete it")
        return redirect(url_for('products.showProduct',
                                category_id=category_id, product_id=product_id))
    if request.method == 'POST':
        session.delete(productToDelete)
        session.commit()
        flash('You successfully deleted \
              product "{}"'.format(productToDelete.name))
        return redirect(url_for('categories.showCategoryProducts',
                                category_id=category_id))
    else:
        return render_template('deleteproduct.html',
                               categories=(category_service
                                           .get_all_categories()),
                               isLogin=auth_service.is_user_authorized(),
                               category=(category_service
                                         .get_category_by_id(category_id)),
                               productToDelete=productToDelete)

project/templates/addcategory.html
{% extends 'main.html' %} {% block content %}
<div class="col-md-9 mt-3">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <h2>Create New Category</h2>
      <form action="#" method="POST">
        <div class="form-group">
          <label for="name">Name:</label>
          <input type="text" id="form_name" class="form-control" name="name" placeholder="Category Name" />
          <div class="invalid-feedback">
            Category Name is required
          </div>
        </div>
        <button type="submit" class="btn btn-success mt-3" id="submit" onclick="checkForm(event)" type="submit">
          Create
        </button>

      </form>
    </div>
  </div>
</div>

<script>
  function checkForm(event) {
    var nameVal = $('#form_name').val().length;
    if (nameVal == 0) {
      event.preventDefault();
    }
    $('#form_name').addClass(nameVal > 0 ? 'is-valid' : 'is-invalid');
  }
</script>
{% endblock %}

project/templates/addproduct.html
{% extends 'main.html' %} {% block content %}
<div class="col-md-9 mt-3">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <h2>Create New Product</h2>
      <form action="#" method="POST" class="mb-5">
        <div class="form-group">
          <label for="name">Name:</label>
          <input type="text" id="form_name" class="form-control mb-2" name="name" placeholder="Product Name">
          <div class="invalid-feedback">
            Name is required
          </div>
        </div>
        <div class="form-group">
          <label for="name">Image URL:</label>
          <input type="text" id="form_image" class="form-control mb-2" name="image_url" placeholder="http://somesource.com/someimage.jpg">
          <div class="invalid-feedback">
            Image URL is required
          </div>
        </div>
        <div class="form-group">
          <label for="name">Original URL:</label>
          <input type="text" id="form_url" class="form-control mb-2" name="product_url" placeholder="http://somesource.com/">
          <div class="invalid-feedback">
            Product URL is required
          </div>
        </div>
        <div class="form-group">
          <label for="category_name">Category:</label>
          <select class="form-control" name="category_name">
            {% for category in categories %}
            <option>{{ category.name }}</option>
            {% endfor %}
          </select>
        </div>
        <div class="form-group">
          <label for="description">Description</label>
          <textarea id="form_description" class="form-control" rows="3" name="description"></textarea>
          <div class="invalid-feedback">
            Description of product is required
          </div>
        </div>
        <button type="submit" class="btn btn-success btn-block mt-3" onclick="checkForm(event)" id="submit" type="submit">
          Create
        </button>
    </div>
    </form>
  </div>
</div>
</div>

<script>
  function checkForm(event) {
    var nameVal = $('#form_name').val().length;
    var imageVal = $('#form_image').val().length;
    var urlVal = $('#form_url').val().length;
    var descVal = $('#form_description').val().length;
    if (nameVal == 0 || imageVal == 0 || urlVal == 0 || descVal == 0) {
      event.preventDefault();
    }
    $('#form_name').addClass(nameVal > 0 ? 'is-valid' : 'is-invalid');
    $('#form_image').addClass(imageVal > 0 ? 'is-valid' : 'is-invalid');
    $('#form_url').addClass(urlVal > 0 ? 'is-valid' : 'is-invalid');
    $('#form_description').addClass(descVal > 0 ? 'is-valid' : 'is-invalid');

  }
</script>
{% endblock %}

project/templates/category.html
{% extends 'main.html' %} {% block content %}
<div class="col-md-9 mt-3">
  <h2 class="mb-3">
    {{ category.name }}
    <span class="text-muted h6">
      {% if countProducts == 1 %}
      ({{ countProducts }} product)
      {% else %}
      ({{ countProducts }} products)
      {% endif %}
    </span>
    {% if isCreator %}
    <a href="{{url_for('categories.editCategory', category_id=category.id)}}" class="h6 text-info">edit</a> <a href="{{url_for('categories.deleteCategory', category_id=category.id)}}"
      class="h6 text-info">delete</a>
    {% endif %}
  </h2>
  {% if isLogin %}
  <p class="text-muted"><i>Creator: {{category.user.name}}</i></p>
  {% endif %}
  <div class="row">
    {% for product in products %}
    <div class="col-sm-6 col-lg-4 mb-4">
      <div class="card">
        <img class="card-img-top img-fluid" src="{{ product.image_url }}" alt="" />
        <div class="card-body">
          <h4 class="card-title">{{ product.name }}</h4>
          <a href="{{url_for('products.showProduct', category_id=category.id, product_id=product.id )}}" class="btn btn-outline-success">Explore</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

{% endblock %}

project/templates/deletecategory.html
{% extends 'main.html' %} {% block content %}
<div class="col-md-9 mt-3">
    <div class="row">
        <div class="col-md-8 offset-md-2 mt-5">
            <h2>Are you sure you want to delete "{{categoryToDelete.name}}" category?</h2>
            <form action="#" method="POST">
                <div class="form-group">
                    <button type="submit" class="btn btn-success mt-3" id="submit" type="submit">
                        Delete
                    </button>
                    <a href="{{url_for('categories.showCategoryProducts', category_id=categoryToDelete.id)}}" class="btn btn-danger mt-3">Cancel</a>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

project/templates/deleteproduct.html
{% extends 'main.html' %} {% block content %}
<div class="col-md-9 mt-3">
    <div class="row">
        <div class="col-md-8 offset-md-2 mt-5">
            <h2>Are you sure you want to delete "{{productToDelete.name}}" product?</h2>
            <form action="#" method="POST">
                <div class="form-group">
                    <button type="submit" class="btn btn-success mt-3" id="submit" type="submit">
                        Delete
                    </button>
                    <a href="{{url_for('products.showProduct', category_id=productToDelete.category_id, product_id=productToDelete.id)}}"
                        class="btn btn-danger mt-3">Cancel</a>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

project/templates/editcategory.html
{% extends 'main.html' %} {% block content %}
<div class="col-md-9 mt-3">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <h2>Edit Category "{{categoryToEdit.name}}"</h2>
            <form action="#" method="POST">
                <div class="form-group">
                    <label for="name">Name:</label>
                    <input id="form_name" type="text" class="form-control" name="name" value="{{categoryToEdit.name}}" />
                    <div class="invalid-feedback">
                        Category Name is required
                    </div>
                </div>
                <button type="submit" class="btn btn-success mt-3" id="submit" onclick="checkForm(event)" type="submit">
                    Edit
                </button>
                <a href="{{url_for('categories.showCategoryProducts', category_id=categoryToEdit.id)}}" class="btn btn-danger mt-3">Cancel</a>
            </form>
        </div>
    </div>
</div>

<script>
    function checkForm(event) {
        var nameVal = $('#form_name').val().length;
        if (nameVal == 0) {
            event.preventDefault();
        }
        $('#form_name').addClass(nameVal > 0 ? 'is-valid' : 'is-invalid');
    }
</script>
{% endblock %}

project/templates/editproduct.html
{% extends 'main.html' %} {% block content %}
<div class="col-md-9 mt-3">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <h2>Edit Product "{{ productToEdit.name }}"</h2>
            <form action="#" method="POST">
                <div class="form-group">
                    <label for="name">Name:</label>
                    <input type="text" class="form-control mb-2" name="name" value="{{ productToEdit.name }}" />
                    <label for="name">Image URL:</label>
                    <input type="text" class="form-control mb-2" name="image_url" value="{{ productToEdit.image_url }}" />
                    <label for="name">Original URL:</label>
                    <input type="text" class="form-control mb-2" name="product_url" value="{{ productToEdit.product_url }}" />
                    <label for="description">Description</label>
                    <textarea class="form-control" rows="3" name="description">{{ productToEdit.description }}</textarea>
                    <button type="submit" class="btn btn-success mt-3" id="submit" type="submit">
                        Edit
                    </button>
                    <a href="{{url_for('products.showProduct', category_id = productToEdit.category_id, product_id=productToEdit.id)}}"
                        class="btn btn-danger mt-3">Cancel</a>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

project/templates/index.html
{% extends 'main.html' %} {% block content %}
<div class="col-md-9 mt-3">


  <h2 class="mb-3">Recently added products</h2>
  <table class="table table-hover">
    <thead>
      <tr class="bg-success text-light">
        <th class="align-middle">Product Name</th>
        <th class="align-middle">Product Category</th>
        <th class="align-middle show-large">Created By</th>
        <th class="align-middle">Link</th>
      </tr>
    </thead>
    <tbody>
      {% for product in latestProducts %}
      <tr>
        <td class="align-middle">{{ product.name }}</td>
        <td class="align-middle text-muted">{{ product.category.name }}</td>
        <td class="align-middle show-large">{{ product.user.name }}</td>
        <td>
          <a href="{{url_for('products.showProduct', category_id=product.category.id, product_id=product.id )}}" class="btn btn-outline-success">Explore</a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>


</div>
{% endblock %}

project/templates/login.html
{% extends 'main.html' %} {% block content %}

<div class="col-md-9 mt-4">
  <div class="my-5">
    <div class="jumbotron text-center bg-light box-shadow">
      <h1 class="h4">Please Sign In</h1>
      <div id="signinButton" class="my-5">
        <button class="g-signin btn btn-outline-dark" data-scope="openid email" data-clientid={{CLIENT_ID}} data-redirecturi="postmessage"
          data-accesstype="offline" data-cookiepolicy="single_host_origin" data-callback="signInCallback"
          data-approvalprompt="force"><img class="mr-1" width="30px" class="mr-2" alt="Google &quot;G&quot; Logo" src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/512px-Google_%22G%22_Logo.svg.png"/><span class="lead">Login with Google</span>
        </button>
      </div>
      <p class="lead">You will be permitted to create, edit or delete categories and products.</p>
    </div>
  </div>
</div>
<!--LOAD PRE-REQUISITES FOR GOOGLE SIGN IN -->
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
<script src="//apis.google.com/js/platform.js?onload=start"></script>
<!-- END PRE-REQUISITES FOR GOOGLE SIGN IN -->

<!-- GOOGLE SIGN IN -->
<script>
  function signInCallback(authResult) {
    if (authResult["code"]) {
      // Hide the sign-in button now that the user is authorized
      $("#signinButton").attr("style", "display: none");
      // Send the one-time-use code to the server, if the server responds,
      // write a 'login successful' message to the web page and then
      // redirect back to the main restaurants page
      $.ajax({
        type: "POST",
        url: "/googleConnect?state={{STATE}}",
        processData: false,
        data: authResult["code"],
        contentType: "application/octet-stream; charset=utf-8",
        success: function (result) {
          // Handle or verify the server response if necessary.
          if (result) {
            window.location.href = "/categories";
          } else if (authResult["error"]) {
            console.log("There was an error: " + authResult["error"]);
          } else {
            $("#result").html(
              "Failed to make a server-side call. Check your configuration and console."
            );
          }
        }
      });
    }
  }
</script>
{% endblock %}

project/templates/product.html
{% extends 'main.html' %} {% block content %}
<div class="col-md-9 mt-3">
  <div class="row">
    <div class="col-lg-6 offset-lg-3 col-sm-8 offset-sm-2 mt-5">
      <div class="card mb-5">
        {% if isCreator %}
        <div class="card-header text-center">
          <a href="{{url_for('products.editProduct', category_id=product.category_id, product_id=product.id)}}" class="h6 text-info px-4">edit</a>
          <a href="{{url_for('products.deleteProduct', category_id=product.category_id, product_id=product.id)}}" class="h6 text-info px-4">delete</a>
        </div>
        {% else %}
        <div class="card-header text-center">
          <i class="text-muted">Created by {{product.user.name}}</i>
        </div>
        {% endif %}
        <img class="card-img-top img-fluid" src="{{ product.image_url }}" alt="" />
        <div class="card-body">
          <h4 class="card-title">{{ product.name }}</h4>
          <p class="lead">{{ product.description }}</p>
          <a href="{{ product.product_url }}" class="btn btn-outline-success btn-block mb-3">Learn More</a>
          <a href="{{url_for('categories.showCategoryProducts', category_id=category.id)}}" class="btn btn-outline-info btn-block">Other
            {{
            category.name }} Products</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}